### ISSUE TITLE
Plugin appears to stop working after a while.

### ISSUE THREAD

**Issue by Mahavo** [ModdedMinecraft/BetterChunkLoader#4]
Hi i love the plugin and it's features.

We have had it a few days now without fault but all of a sudden it's started to error at random times but fixes upon a server restart.

Here is the error it generates when someone joins or you do /bcl reload data
https://pastebin.com/5gYqVey9

Thank you

**Comment by leelawd** [comment]
Unable to reproduce this in any instance, if this is still a problem, please open a new issue.
